require "spec_helper"
require "net/http"
require "lutaml/model/schema"
require "support/xml/schema_helper"

RSpec.describe Lutaml::Model::Schema::XmlCompiler do
  # Reset :default context before each test to prevent pollution
  # Each test generates classes that register in :default context,
  # so we need a clean slate with only built-in types
  before do
    default_ctx = Lutaml::Model::GlobalContext.context(:default)
    if default_ctx
      # Clear all registered types and re-add only built-in types
      default_ctx.registry.clear
      Lutaml::Model::Type.register_builtin_types_in(default_ctx.registry)
    end
  end

  # Helper method to strip XML comments for comparison
  # Loop to handle nested/adjacent comments that may create new <!-- patterns
  def strip_xml_comments(xml)
    previous = nil
    current = xml
    while current != previous
      previous = current
      current = current.gsub(/<!--.*?-->/m, "")
    end
    current
  end

  describe ".as_models" do
    let(:xml_namespace_schema) do
      <<~XSD
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                   targetNamespace="http://www.w3.org/XML/1998/namespace">
          <xs:attribute name="id" type="xs:ID"/>
        </xs:schema>
      XSD
    end

    it "keeps built-in W3C XML attribute types when processing xml.xsd" do
      described_class.as_models(xml_namespace_schema)

      type_ref = described_class.builder.attributes["id"].type
      expect(type_ref.kind).to eq(:w3c)
      expect(type_ref.value).to eq("Lutaml::Xml::W3c::XmlIdType")
    end
  end

  describe ".to_models" do
    describe "Testing the unofficial schemas" do
      context "with valid xml schema, it generates the models" do
        before do
          described_class.to_models(schema, output_dir: dir,
                                            create_files: true, module_namespace: "MathTestSpec")
          require File.join(dir, "mathtestspec_registry.rb")
          MathTestSpec.register_all
        end

        after do
          FileUtils.rm_rf(dir)
          Object.send(:remove_const, :MathTestSpec) if defined?(MathTestSpec)
        end

        let(:dir) { Dir.mktmpdir }

        let(:schema) { File.read("spec/fixtures/xml/test_schema.xsd") }

        let(:valid_value_xml_example) do
          <<~VALID_XML_EXAMPLE
            <CT_MathTest>
              <MathTest val="1"/>
              <MathTest1 val="1"/>
            </CT_MathTest>
          VALID_XML_EXAMPLE
        end

        let(:invalid_value_xml_example) do
          <<~INVALID_XML_EXAMPLE
            <CT_MathTest>
              <MathTest val="0"/>
              <MathTest1 val="-3"/>
            </CT_MathTest>
          INVALID_XML_EXAMPLE
        end

        it "validates if the files exist in the module directory" do
          module_dir = File.join(dir, "mathtestspec")
          expect(File).to exist("#{module_dir}/ct_math_test.rb")
          expect(File).to exist("#{module_dir}/st_integer255.rb")
          expect(File).to exist("#{module_dir}/long.rb")
        end

        it "validates if the CTMathTest class is loaded" do
          expect(defined?(MathTestSpec::CTMathTest)).to eq("constant")
        end

        it "creates the model files, requires them, and tests them with valid and invalid xml" do
          expect(MathTestSpec::CTMathTest.from_xml(valid_value_xml_example).to_xml).to be_xml_equivalent_to(valid_value_xml_example)
        end

        it "raises error when processing invalid example" do
          expect do
            MathTestSpec::CTMathTest.from_xml(invalid_value_xml_example)
          end.to raise_error(Lutaml::Model::Type::MinBoundError)
        end
      end

      context "when processing examples from classes/files generated by valid xml schema" do
        let!(:math_doc_dir) { Dir.mktmpdir }
        let(:valid_example) do
          File.read("spec/fixtures/xml/valid_math_document.xml")
        end
        let(:invalid_example) do
          File.read("spec/fixtures/xml/invalid_math_document.xml")
        end

        before do
          described_class.to_models(
            File.read("spec/fixtures/xml/math_document_schema.xsd"),
            output_dir: math_doc_dir,
            create_files: true,
            module_namespace: "MathDocSpec",
          )
          require File.join(math_doc_dir, "mathdocspec_registry.rb")
          MathDocSpec.register_all
        end

        after do
          FileUtils.rm_rf(math_doc_dir)
          Object.send(:remove_const, :MathDocSpec) if defined?(MathDocSpec)
        end

        it "does not raise error with valid example and creates files" do
          expect(defined?(MathDocSpec::MathDocument)).to eq("constant")
          parsed = MathDocSpec::MathDocument.from_xml(valid_example)
          expect(parsed.title).to eql("Example Title")
          expect(parsed.ipv4_address).to eql("192.168.1.1")
          expect(parsed.to_xml).to be_xml_equivalent_to(valid_example)
        end

        it "raises PatternNotMatchedError" do
          expect(defined?(MathDocSpec::MathDocument)).to eq("constant")
          expect { MathDocSpec::MathDocument.from_xml(invalid_example) }
            .to raise_error(Lutaml::Model::Type::PatternNotMatchedError)
        end
      end

      context "when compiling constraining facets (issue #191 from_xsd)" do
        let!(:facets_dir) { Dir.mktmpdir }
        let(:item) { RestrictionFacetsSpec::CTItem }

        before do
          described_class.to_models(
            File.read("spec/fixtures/xml/restriction_facets.xsd"),
            output_dir: facets_dir,
            create_files: true,
            module_namespace: "RestrictionFacetsSpec",
          )
          require File.join(facets_dir, "restrictionfacetsspec_registry.rb")
          RestrictionFacetsSpec.register_all
        end

        after do
          FileUtils.rm_rf(facets_dir)
          if defined?(RestrictionFacetsSpec)
            Object.send(:remove_const, :RestrictionFacetsSpec)
          end
        end

        it "validates a fully in-range item with no errors" do
          model = item.new(code: "ab", ratio: 50, price: "123.45",
                           moment: "2020-06-15T12:00:00")
          expect(model.validate).to be_empty
        end

        it "collects a MinLengthError for a too-short string (minLength)" do
          expect(item.new(code: "a").validate.first)
            .to be_a(Lutaml::Model::MinLengthError)
        end

        it "collects a MaxLengthError for a too-long string (maxLength)" do
          expect(item.new(code: "toolongvalue").validate.first)
            .to be_a(Lutaml::Model::MaxLengthError)
        end

        it "collects a MaxExclusiveError at the exclusive upper bound" do
          expect(item.new(ratio: 100).validate.first)
            .to be_a(Lutaml::Model::MaxExclusiveError)
        end

        it "collects a MinExclusiveError at the exclusive lower bound" do
          expect(item.new(ratio: 0).validate.first)
            .to be_a(Lutaml::Model::MinExclusiveError)
        end

        it "collects a TotalDigitsError beyond the total-digit cap" do
          expect(item.new(price: "1234.56").validate.first)
            .to be_a(Lutaml::Model::TotalDigitsError)
        end

        it "collects a FractionDigitsError beyond the fraction-digit cap" do
          expect(item.new(price: "1.234").validate.first)
            .to be_a(Lutaml::Model::FractionDigitsError)
        end

        it "collects a MinInclusiveError before the temporal lower bound" do
          expect(item.new(moment: "2019-12-31T00:00:00").validate.first)
            .to be_a(Lutaml::Model::MinInclusiveError)
        end

        it "accepts a boolean value allowed by a cast enumeration" do
          expect(item.new(flag: true).validate).to be_empty
        end

        it "collects an InvalidValueError for a disallowed boolean enum value" do
          expect(item.new(flag: false).validate.first)
            .to be_a(Lutaml::Model::InvalidValueError)
        end

        it "normalizes whitespace at cast time (whiteSpace collapse)" do
          expect(item.new(label: "  a   b  ").label).to eq("a b")
        end

        it "carries the error attribute name" do
          error = item.new(code: "a").validate.first
          expect(error.to_s).to include("code")
        end
      end

      context "when compiling a built-in interpolated pattern (issue #191 anyURI)" do
        let!(:uri_dir) { Dir.mktmpdir }
        let(:link) { AnyUriPatternSpec::CTLink }
        let(:uri_schema) do
          <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:complexType name="CT_Link">
                <xsd:attribute name="href" type="xsd:anyURI" />
              </xsd:complexType>
              <xsd:element name="Link" type="CT_Link" />
            </xsd:schema>
          XSD
        end

        before do
          described_class.to_models(
            uri_schema,
            output_dir: uri_dir,
            create_files: true,
            module_namespace: "AnyUriPatternSpec",
          )
          require File.join(uri_dir, "anyuripatternspec_registry.rb")
          AnyUriPatternSpec.register_all
        end

        after do
          FileUtils.rm_rf(uri_dir)
          if defined?(AnyUriPatternSpec)
            Object.send(:remove_const, :AnyUriPatternSpec)
          end
        end

        # Regression: the lazy pattern facet must keep the built-in anyURI
        # pattern's live `#{...}` interpolation, else every valid URI is
        # falsely rejected at validate time.
        it "accepts a valid URI through the lazy interpolated pattern facet" do
          expect(link.new(href: "http://example.com/a?b=1").validate)
            .to be_empty
        end

        it "rejects an invalid URI at cast time" do
          expect { link.new(href: "has spaces here") }
            .to raise_error(Lutaml::Model::Type::PatternNotMatchedError)
        end
      end

      context "when a restriction repeats a bound (issue #191 tightest-wins)" do
        let(:tight_schema) do
          <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:simpleType name="Tight">
                <xsd:restriction base="xsd:integer">
                  <xsd:minExclusive value="5" />
                  <xsd:minExclusive value="10" />
                  <xsd:maxExclusive value="99" />
                  <xsd:maxExclusive value="90" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:schema>
          XSD
        end

        # Exclusive bounds must tighten like the inclusive ones: the largest
        # lower bound and smallest upper bound win, so no out-of-range value
        # slips through the generated facets.
        it "carries the tightest exclusive bounds" do
          code = described_class.to_models(tight_schema).fetch("Tight")
          expect(code).to include("exclusive min: 10, max: 90")
        end

        it "orders repeated decimal bounds numerically, not lexically" do
          schema = <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:simpleType name="D">
                <xsd:restriction base="xsd:decimal">
                  <xsd:minInclusive value="9.5" />
                  <xsd:minInclusive value="10.5" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:schema>
          XSD
          code = described_class.to_models(schema).fetch("D")
          expect(code).to include('inclusive min: BigDecimal("10.5")')
        end
      end

      context "when a restriction derives from a user-defined atomic type " \
              "(issue #191 chained base)" do
        # Deriving a tighter type from a named numeric/decimal/temporal type is
        # valid, common XSD. The further restriction's base is the user type
        # (not a built-in), so its bound/enumeration must render through the
        # parent's `cast` — a bare string would crash `<=>`/never equal the
        # cast value at validation.
        let(:chained_schema) do
          <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:simpleType name="Amount">
                <xsd:restriction base="xsd:integer">
                  <xsd:minInclusive value="0" />
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType name="SmallAmount">
                <xsd:restriction base="Amount">
                  <xsd:maxInclusive value="100" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:schema>
          XSD
        end

        it "renders the chained bound through the parent type's cast" do
          code = described_class.to_models(chained_schema).fetch("SmallAmount")
          expect(code).to include('inclusive max: Amount.cast("100")')
        end

        it "renders a chained enumeration through the parent type's cast" do
          schema = <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:simpleType name="Amount">
                <xsd:restriction base="xsd:integer">
                  <xsd:minInclusive value="0" />
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType name="Choice">
                <xsd:restriction base="Amount">
                  <xsd:enumeration value="5" />
                  <xsd:enumeration value="10" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:schema>
          XSD
          code = described_class.to_models(schema).fetch("Choice")
          expect(code).to include("enumeration(Amount.cast(\"5\"), Amount.cast(\"10\"))")
        end
      end

      context "when compiling non-integer atomic bases (issue #191)" do
        let!(:atomic_dir) { Dir.mktmpdir }
        let(:atomic_schema) do
          <<~XSD
            <?xml version="1.0" encoding="utf-8"?>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
              <xsd:simpleType name="ST_Money">
                <xsd:restriction base="xsd:decimal">
                  <xsd:minExclusive value="1.5" />
                  <xsd:maxExclusive value="9.5" />
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType name="ST_Rate">
                <xsd:restriction base="xsd:float">
                  <xsd:minInclusive value="1.25" />
                  <xsd:maxInclusive value="9.75" />
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:simpleType name="ST_Day">
                <xsd:restriction base="xsd:date">
                  <xsd:minInclusive value="2020-01-01" />
                </xsd:restriction>
              </xsd:simpleType>
              <xsd:complexType name="CT_Rec">
                <xsd:attribute name="money" type="ST_Money" />
                <xsd:attribute name="rate" type="ST_Rate" />
                <xsd:attribute name="day" type="ST_Day" />
              </xsd:complexType>
              <xsd:element name="Rec" type="CT_Rec" />
            </xsd:schema>
          XSD
        end
        let(:rec) { AtomicBasesSpec::CTRec }

        before do
          described_class.to_models(
            atomic_schema,
            output_dir: atomic_dir,
            create_files: true,
            module_namespace: "AtomicBasesSpec",
          )
          require File.join(atomic_dir, "atomicbasesspec_registry.rb")
          AtomicBasesSpec.register_all
        end

        after do
          FileUtils.rm_rf(atomic_dir)
          if defined?(AtomicBasesSpec)
            Object.send(:remove_const, :AtomicBasesSpec)
          end
        end

        # Regression: decimal facet values must keep their exact lexical form
        # (the exclusive facets used to parse `value` as an integer, truncating
        # 1.5 to 1). At the exact bound 1.5 the eager inclusive cast passes and
        # the lazy exclusive facet rejects — proving the bound is 1.5, not 1.
        it "preserves decimal precision on exclusive bounds" do
          expect(rec.new(money: "5.0").validate).to be_empty
          expect(rec.new(money: "1.5").validate.first)
            .to be_a(Lutaml::Model::MinExclusiveError)
        end

        # Regression: xsd:float/xsd:date were absent from the supported-type map,
        # so a faceted restriction generated a class inheriting Ruby-core
        # Float/Date and failed to load. They now map to the Lutaml types. A
        # below-range float is rejected by the eager numeric cast.
        it "compiles a float restriction that loads and enforces bounds" do
          expect(rec.new(rate: 5.0).validate).to be_empty
          expect { rec.new(rate: 0.5) }
            .to raise_error(Lutaml::Model::Type::MinBoundError)
        end

        it "compiles a date restriction that loads and enforces bounds" do
          expect(rec.new(day: "2020-06-01").validate).to be_empty
          expect(rec.new(day: "2019-06-01").validate.first)
            .to be_a(Lutaml::Model::MinInclusiveError)
        end
      end

      context "when processing example from lutaml-model#260" do
        let!(:address_dir) { Dir.mktmpdir }
        let(:address) do
          <<~ADD
            <Address>
              Oxford Street
              <City>London</City>
              <ZIP>E1 6AN</ZIP>
            </Address>
          ADD
        end

        before do
          described_class.to_models(
            File.read("spec/fixtures/xml/address_example_260.xsd"),
            output_dir: address_dir,
            create_files: true,
            module_namespace: "CompilerSpec260",
          )
          require File.join(address_dir, "compilerspec260_registry.rb")
          CompilerSpec260.register_all
        end

        after do
          FileUtils.rm_rf(address_dir)
          if defined?(CompilerSpec260)
            Object.send(:remove_const,
                        :CompilerSpec260)
          end
        end

        it "matches parsed xml with input" do
          expect(defined?(CompilerSpec260::Address)).to eq("constant")
          expect(CompilerSpec260::Address.from_xml(address).to_xml).to be_xml_equivalent_to(address)
        end
      end

      context "when processing example from files generated by schema -> product_catalog.xsd" do
        let!(:catalog_dir) { Dir.mktmpdir }
        let(:product_catalog) do
          File.read("spec/fixtures/xml/examples/valid_catalog.xml")
        end
        let(:nested_category) do
          File.read("spec/fixtures/xml/examples/nested_categories.xml")
        end

        before do
          described_class.to_models(
            File.read("spec/fixtures/xml/product_catalog.xsd"),
            output_dir: catalog_dir,
            create_files: true,
            module_namespace: "CatalogSpec",
          )
          require File.join(catalog_dir, "catalogspec_registry.rb")
          CatalogSpec.register_all
        end

        after do
          FileUtils.rm_rf(catalog_dir)
          Object.send(:remove_const, :CatalogSpec) if defined?(CatalogSpec)
        end

        it "confirms the ProductCatalog class is required" do
          expect(defined?(CatalogSpec::ProductCatalog)).to eq("constant")
        end

        it "confirms that the from_xml and to_xml methods successfully handles xml for valid_catalog.xml" do
          expect(CatalogSpec::ProductCatalog.from_xml(product_catalog).to_xml).to be_a(String)
        end

        it "confirms that the from_xml and to_xml methods successfully handles xml for nested_categories.xml" do
          expect(CatalogSpec::ProductCatalog.from_xml(nested_category).to_xml).to be_a(String)
        end
      end

      context "when classes are generated but files are not created" do
        let(:schema_classes_hash) do
          described_class.to_models(File.read("spec/fixtures/xml/user.xsd"),
                                    module_namespace: nil)
        end

        let(:expected_classes) do
          classes = described_class::SupportedDataTypes::TABLE.filter_map do |name, value|
            name.to_s unless value[:skippable]
          end
          classes << "User"
          # W3C xml: namespace is now built-in, no custom class generated
          classes.sort
        end

        it "matches the expected class names of the schema" do
          expect(schema_classes_hash.keys.sort).to eql(expected_classes)
        end
      end

      context "when classes are generated and loaded but files are not created" do
        before do
          described_class.to_models(
            File.read("spec/fixtures/xml/user.xsd"),
            load_classes: true,
            module_namespace: nil,
          )
        end

        let(:expected_classes) do
          %w[
            NonNegativeInteger
            PositiveInteger
            Base64Binary
            UnsignedLong
            UnsignedInt
            HexBinary
            Token
            Long
            User
          ]
        end

        let(:xml) do
          <<~XML
            <User>
              <id>1112</id>
              <age>29</age>
              <token>u9dId901dp13f</token>
            </User>
          XML
        end

        it "matches the expected class names of the schema" do
          expected_classes.each do |klass|
            expect(be_const_defined(klass)).to be_truthy
          end
          expect(User.from_xml(xml).to_xml).to be_xml_equivalent_to(xml)
        end
      end

      context "when classes are generated and loaded but files are not created for specifications schema" do
        before do
          described_class.to_models(schema, load_classes: true,
                                            module_namespace: nil)
        end

        let(:schema) do
          File.read("spec/fixtures/xml/specifications_schema.xsd")
        end

        let(:spec_xml) do
          <<~XML
            <spec>
              <title>Example Specification</title>
              <version>1.0</version>
              <status>draft</status>
            </spec>
          XML
        end

        let(:short_spec_xml) do
          <<~XML
            <shortSpec>
              <title>Example Specification</title>
              <version>1.0</version>
              <status>draft</status>
            </shortSpec>
          XML
        end

        after do
          # Clean up dynamically generated classes to prevent test pollution
          Object.send(:remove_const, :Spec) if defined?(Spec)
          Object.send(:remove_const, :ShortSpec) if defined?(ShortSpec)
        end

        it "successfully processes the Spec example" do
          expect(Spec.from_xml(spec_xml).to_xml).to be_xml_equivalent_to(spec_xml)
        end

        it "successfully processes the ShortSpec example" do
          expect(ShortSpec.from_xml(short_spec_xml).to_xml).to be_xml_equivalent_to(short_spec_xml)
        end
      end
    end

    describe "Testing the official schemas" do
      context "when classes are generated and loaded but files are not created for OOXML schema" do
        before do
          Lutaml::Model::GlobalRegister.register(Lutaml::Model::Register.new(register_id))
          Lutaml::Model::Config.default_register = register_id

          described_class.to_models(
            Net::HTTP.get(URI("#{schema_location}/shared-math.xsd")),
            location: schema_location,
            namespace: "http://schemas.openxmlformats.org/officeDocument/2006/math",
            module_namespace: "OOXML",
            register_id: :ooxml,
            output_dir: dir,
            create_files: true,
          )
          require File.join(dir, "ooxml_registry.rb")
          OOXML.register_all
        end

        after do
          Lutaml::Model::Config.default_register = :default
          FileUtils.rm_rf(dir)
          # Clean up dynamically generated register to prevent test pollution
          Lutaml::Model::GlobalRegister.unregister(:ooxml) if Lutaml::Model::GlobalRegister.lookup(:ooxml)
          Object.send(:remove_const, :OOXML) if defined?(OOXML)
        end

        let(:register_id) { :ooxml }
        let(:dir) { Dir.mktmpdir }
        let(:schema_location) { "https://raw.githubusercontent.com/t-yuki/ooxml-xsd/refs/heads/master" }

        let(:xml) do
          <<~XML
            <m:CT_F xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">
              <m:fPr>
                <m:type val="noBar"/>
              </m:fPr>
              <m:num>
                <m:r/>
              </m:num>
              <m:den>
                <m:r/>
              </m:den>
            </m:CT_F>
          XML
        end

        it "matches the expected class names of the schema" do
          # Session 101 fixed namespace prefix issue for reused child elements
          # Session 114 fixed performance with recursive import resolution
          # Session 115 fixed circular requires with module namespacing and autoload
          # register_all resolves all imports, so attributes are populated
          expect(defined?(OOXML::CTOMath)).to eq("constant")
          expect(OOXML::CTOMath.attributes(:ooxml)).not_to be_empty
          expect(OOXML::CTF.from_xml(xml).to_xml(prefix: "m")).to be_xml_equivalent_to(xml)
          expect(OOXML::CTF.attributes(:ooxml)).not_to be_empty
        end
      end

      context "when classes are generated and loaded but files are not created for UnitsML-v0.9.19 schema" do
        before do
          Lutaml::Model::GlobalRegister.register(Lutaml::Model::Register.new(register_id))
          Lutaml::Model::Config.default_register = register_id

          described_class.to_models(
            Net::HTTP.get(URI(schema_url)),
            namespace: "http://unitsml.nist.gov/unitsml-v0.9.19",
            module_namespace: "UnitsMLV0919",
            register_id: :unitsmlv0919,
            output_dir: dir,
            create_files: true,
          )
          require File.join(dir, "unitsmlv0919_registry.rb")
          UnitsMLV0919.register_all
        end

        after do
          Lutaml::Model::Config.default_register = :default
          FileUtils.rm_rf(dir)
          # Clean up dynamically generated register to prevent test pollution
          Lutaml::Model::GlobalRegister.unregister(:unitsmlv0919) if Lutaml::Model::GlobalRegister.lookup(:unitsmlv0919)
          Object.send(:remove_const, :UnitsMLV0919) if defined?(UnitsMLV0919)
        end

        let(:register_id) { :unitsmlv0919 }
        let(:dir) { Dir.mktmpdir }
        let(:schema_url) { "https://raw.githubusercontent.com/unitsml/schemas/refs/heads/main/unitsml/unitsml-v0.9.19.xsd" }

        let(:xml) do
          <<~XML
            <UnitsMLType xmlns="http://unitsml.nist.gov/unitsml-v0.9.19">
              <UnitSet>
                <Unit>
                  <UnitSystem type="SI"/>
                  <UnitName xml:lang="en">meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                </Unit>
              </UnitSet>
            </UnitsMLType>
          XML
        end

        let(:detailed_xml) do
          <<~XML
            <UnitsMLType xmlns="http://unitsml.nist.gov/unitsml-v0.9.19">
              <!-- Units -->
              <UnitSet>
                <!-- Base unit: meter -->
                <Unit xml:id="u1" timeStamp="2024-06-01T00:00:00Z" dimensionURL="http://unitsml.nist.gov/si/length">
                  <UnitSystem name="SI" type="SI_base"/>
                  <UnitName>meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                  <UnitVersionHistory>Initial definition</UnitVersionHistory>
                  <CodeListValue unitCodeValue="MTR" codeListName="UN/ECE Rec 20" codeListVersion="10A" locationURL="https://unece.org/trade/cefact/UNLOCODE-Download" organizationName="UNECE"/>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                  </RootUnits>
                  <UnitDefinition sourceName="SI Brochure" sourceURL="https://www.bipm.org/en/publications/si-brochure">The meter is the SI unit of length.</UnitDefinition>
                  <UnitHistory>Defined as the distance light travels in vacuum in 1/299792458 seconds.</UnitHistory>
                  <UnitRemark>Most common length unit</UnitRemark>
                </Unit>

                <!-- Derived unit: meter per second -->
                <Unit xml:id="u2" timeStamp="2024-06-01T00:00:00Z" dimensionURL="http://unitsml.nist.gov/si/speed">
                  <UnitSystem name="SI" type="SI_derived"/>
                  <UnitName>meter per second</UnitName>
                  <UnitSymbol type="ASCII">m/s</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                    <EnumeratedRootUnit unit="second" powerNumerator="-1"/>
                  </RootUnits>
                  <Conversions>
                    <Float64ConversionFrom xml:id="c1" initialUnit="http://example.com/units#u3" initialAddend="0.0" multiplicand="3.6" divisor="1.0" finalAddend="0.0" exact="true">
                      <ConversionNote>Convert from kilometers per hour to meters per second</ConversionNote>
                    </Float64ConversionFrom>
                  </Conversions>
                  <QuantityReference url="http://example.com/units#q2" name="speed"/>
                  <UnitDefinition>Speed unit in SI</UnitDefinition>
                </Unit>

                <!-- Non-SI unit: kilometer per hour -->
                <Unit xml:id="u3" timeStamp="2024-06-01T00:00:00Z" dimensionURL="http://unitsml.nist.gov/si/speed">
                  <UnitSystem name="SI" type="non-SI_accepted"/>
                  <UnitName>kilometer per hour</UnitName>
                  <UnitSymbol type="ASCII">km/h</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter" prefix="k"/>
                    <EnumeratedRootUnit unit="second" powerNumerator="-1"/>
                    <EnumeratedRootUnit unit="hour" powerNumerator="-1"/>
                  </RootUnits>
                  <Conversions>
                    <Float64ConversionFrom xml:id="c2" initialUnit="http://example.com/units#u2" initialAddend="0.0" multiplicand="1.0" divisor="3.6" finalAddend="0.0" exact="true">
                      <ConversionNote>Convert from meters per second to kilometers per hour</ConversionNote>
                    </Float64ConversionFrom>
                  </Conversions>
                  <QuantityReference url="http://example.com/units#q2" name="speed"/>
                  <UnitDefinition>Common speed unit for vehicles</UnitDefinition>
                </Unit>
              </UnitSet>

              <!-- Quantities -->
              <QuantitySet>
                <Quantity xml:id="q1" quantityType="base" dimensionURL="http://unitsml.nist.gov/si/length">
                  <QuantityName>length</QuantityName>
                  <QuantitySymbol type="ASCII">l</QuantitySymbol>
                  <UnitReference url="http://example.com/units#u1" name="meter"/>
                  <QuantityDefinition sourceName="SI Brochure" sourceURL="https://www.bipm.org/en/publications/si-brochure">Distance between two points</QuantityDefinition>
                  <QuantityRemark>SI base quantity</QuantityRemark>
                </Quantity>
                <Quantity xml:id="q2" quantityType="derived" dimensionURL="http://unitsml.nist.gov/si/speed">
                  <QuantityName>speed</QuantityName>
                  <QuantitySymbol type="ASCII">v</QuantitySymbol>
                  <UnitReference url="http://example.com/units#u2" name="meter per second"/>
                  <QuantityDefinition>Rate of change of position</QuantityDefinition>
                </Quantity>
              </QuantitySet>

              <!-- Dimensions -->
              <DimensionSet>
                <Dimension xml:id="d1">
                  <Length powerNumerator="1"/>
                </Dimension>
                <Dimension xml:id="d2">
                  <Length powerNumerator="1"/>
                  <Time powerNumerator="-1"/>
                </Dimension>
                <Dimension xml:id="d3" dimensionless="true"/>
                <Dimension xml:id="d4">
                  <Time powerNumerator="-1"/>
                  <Item itemURL="http://example.com/items#ci1" itemSymbol="e⁻" powerNumerator="1"/>
                </Dimension>
              </DimensionSet>

              <!-- Prefixes -->
              <PrefixSet>
                <Prefix xml:id="p1" prefixBase="10" prefixPower="3">
                  <PrefixName>kilo</PrefixName>
                  <PrefixSymbol type="ASCII">k</PrefixSymbol>
                </Prefix>
                <Prefix xml:id="p2" prefixBase="2" prefixPower="10">
                  <PrefixName>kibi</PrefixName>
                  <PrefixSymbol type="ASCII">Ki</PrefixSymbol>
                </Prefix>
              </PrefixSet>
            </UnitsMLType>
          XML
        end

        it "matches the converted xml with the expected xml with a short example" do
          expect(UnitsMLV0919::UnitsMLType.from_xml(xml).to_xml).to be_xml_equivalent_to(xml)
        end

        it "matches the converted xml with the expected xml with a detailed example" do
          actual = UnitsMLV0919::UnitsMLType.from_xml(detailed_xml).to_xml
          expect(strip_xml_comments(actual)).to be_xml_equivalent_to(strip_xml_comments(detailed_xml))
        end
      end

      context "when classes are generated and loaded but files are not created for UnitsML-v1.0-csd03 schema" do
        before do
          Lutaml::Model::GlobalRegister.register(Lutaml::Model::Register.new(register_id))
          Lutaml::Model::Config.default_register = register_id

          described_class.to_models(
            Net::HTTP.get(URI(schema_url)),
            module_namespace: "UnitsMLV10CSD03",
            register_id: :unitsml_v1_0_csd03,
            output_dir: dir,
            create_files: true,
          )
          require File.join(dir, "unitsmlv10csd03_registry.rb")
          UnitsMLV10CSD03.register_all
        end

        after do
          Lutaml::Model::Config.default_register = :default
          FileUtils.rm_rf(dir)
          # Clean up dynamically generated register to prevent test pollution
          Lutaml::Model::GlobalRegister.unregister(:unitsml_v1_0_csd03) if Lutaml::Model::GlobalRegister.lookup(:unitsml_v1_0_csd03)
          if defined?(UnitsMLV10CSD03)
            Object.send(:remove_const,
                        :UnitsMLV10CSD03)
          end
        end

        let(:register_id) { :unitsml_v1_0_csd03 }
        let(:dir) { Dir.mktmpdir }
        let(:schema_url) { "https://raw.githubusercontent.com/unitsml/schemas/refs/heads/main/unitsml/unitsml-v1.0-csd03.xsd" }

        let(:xml) do
          <<~XML
            <UnitsMLType>
              <UnitSet>
                <Unit xml:id="U_m">
                  <UnitSystem type="SI"/>
                  <UnitName xml:lang="en">meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                </Unit>
                <Unit xml:id="U_km">
                  <UnitSystem type="SI"/>
                  <UnitName xml:lang="en">kilometer</UnitName>
                  <UnitSymbol type="ASCII">km</UnitSymbol>
                </Unit>
              </UnitSet>
            </UnitsMLType>
          XML
        end

        let(:detailed_xml) do
          <<~XML
            <UnitsMLType>
              <UnitSet>
                <Unit xml:id="u_meter" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/meter">
                  <UnitSystem name="SI" type="SI_base"/>
                  <UnitName xml:lang="en">meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                  <CodeListValue unitCodeValue="MTR" codeListName="UN/ECE Rec 20" codeListVersion="10A" locationURL="http://www.unece.org/cefact/codesfortrade/codes_index.html" organizationName="UNECE"/>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                  </RootUnits>
                  <UnitVersionHistory>Initial definition of the meter.</UnitVersionHistory>
                  <UnitDefinition>The meter is the SI base unit of length.</UnitDefinition>
                  <UnitHistory>Defined as the distance light travels in vacuum in 1/299792458 seconds.</UnitHistory>
                  <UnitRemark>Commonly used in science and engineering.</UnitRemark>
                </Unit>
                <Unit xml:id="u_second" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/second">
                  <UnitSystem name="SI" type="SI_base"/>
                  <UnitName xml:lang="en">second</UnitName>
                  <UnitSymbol type="ASCII">s</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="second"/>
                  </RootUnits>
                </Unit>
                <Unit xml:id="u_newton" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/newton">
                  <UnitSystem name="SI" type="SI_derived"/>
                  <UnitName xml:lang="en">newton</UnitName>
                  <UnitSymbol type="ASCII">N</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                    <EnumeratedRootUnit unit="gram"/>
                    <EnumeratedRootUnit unit="second" powerNumerator="-2"/>
                  </RootUnits>
                  <Conversions>
                    <Float64ConversionFrom xml:id="conv1" initialUnit="http://unitsml.nist.gov/si/meter#u_gram_meter_per_second_squared" multiplicand="1.0" divisor="1.0" exact="true"/>
                  </Conversions>
                </Unit>
              </UnitSet>
            </UnitsMLType>
          XML
        end

        it "matches the converted xml with the expected xml with a short example" do
          expect(UnitsMLV10CSD03::UnitsMLType.from_xml(xml).to_xml).to be_xml_equivalent_to(xml)
        end

        it "matches the converted xml with the expected xml with a detailed example" do
          expect(UnitsMLV10CSD03::UnitsMLType.from_xml(detailed_xml).to_xml).to be_xml_equivalent_to(detailed_xml)
        end
      end

      context "when classes are generated and loaded but files are not created for UnitsML-v1.0-csd04 schema" do
        before do
          Lutaml::Model::GlobalRegister.register(Lutaml::Model::Register.new(register_id))
          Lutaml::Model::Config.default_register = register_id

          described_class.to_models(
            Net::HTTP.get(URI(schema_url)),
            module_namespace: "UnitsMLV10CSD04",
            register_id: :unitsml_v1_0_csd04,
            output_dir: dir,
            create_files: true,
          )
          require File.join(dir, "unitsmlv10csd04_registry.rb")
          UnitsMLV10CSD04.register_all
        end

        after do
          Lutaml::Model::Config.default_register = :default
          FileUtils.rm_rf(dir)
          # Clean up dynamically generated register to prevent test pollution
          Lutaml::Model::GlobalRegister.unregister(:unitsml_v1_0_csd04) if Lutaml::Model::GlobalRegister.lookup(:unitsml_v1_0_csd04)
          if defined?(UnitsMLV10CSD04)
            Object.send(:remove_const,
                        :UnitsMLV10CSD04)
          end
        end

        let(:register_id) { :unitsml_v1_0_csd04 }
        let(:dir) { Dir.mktmpdir }
        let(:schema_url) { "https://raw.githubusercontent.com/unitsml/schemas/refs/heads/main/unitsml/unitsml-v1.0-csd04.xsd" }

        let(:xml) do
          <<~XML
            <UnitsMLType>
              <UnitSet>
                <Unit xml:id="U_m">
                  <UnitSystem type="SI"/>
                  <UnitName xml:lang="en">meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                </Unit>
                <Unit xml:id="U_km">
                  <UnitSystem type="SI"/>
                  <UnitName xml:lang="en">kilometer</UnitName>
                  <UnitSymbol type="ASCII">km</UnitSymbol>
                </Unit>
              </UnitSet>
            </UnitsMLType>
          XML
        end

        let(:detailed_xml) do
          <<~XML
            <UnitsMLType>
              <UnitSet>
                <Unit xml:id="u_meter" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/meter">
                  <UnitSystem name="SI" type="SI_base"/>
                  <UnitName xml:lang="en">meter</UnitName>
                  <UnitSymbol type="ASCII">m</UnitSymbol>
                  <CodeListValue unitCodeValue="MTR" codeListName="UN/ECE Rec 20" codeListVersion="10A" locationURL="http://www.unece.org/cefact/codesfortrade/codes_index.html" organizationName="UNECE"/>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                  </RootUnits>
                  <UnitVersionHistory>Initial definition of the meter.</UnitVersionHistory>
                  <UnitDefinition>The meter is the SI base unit of length.</UnitDefinition>
                  <UnitHistory>Defined as the distance light travels in vacuum in 1/299792458 seconds.</UnitHistory>
                  <UnitRemark>Commonly used in science and engineering.</UnitRemark>
                </Unit>
                <Unit xml:id="u_second" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/second">
                  <UnitSystem name="SI" type="SI_base"/>
                  <UnitName xml:lang="en">second</UnitName>
                  <UnitSymbol type="ASCII">s</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="second"/>
                  </RootUnits>
                </Unit>
                <Unit xml:id="u_newton" timeStamp="2024-06-01T12:00:00Z" dimensionURL="http://unitsml.nist.gov/si/newton">
                  <UnitSystem name="SI" type="SI_derived"/>
                  <UnitName xml:lang="en">newton</UnitName>
                  <UnitSymbol type="ASCII">N</UnitSymbol>
                  <RootUnits>
                    <EnumeratedRootUnit unit="meter"/>
                    <EnumeratedRootUnit unit="gram"/>
                    <EnumeratedRootUnit unit="second" powerNumerator="-2"/>
                  </RootUnits>
                  <Conversions>
                    <Float64ConversionFrom xml:id="conv1" initialUnit="http://unitsml.nist.gov/si/meter#u_gram_meter_per_second_squared" multiplicand="1.0" divisor="1.0" exact="true"/>
                  </Conversions>
                </Unit>
              </UnitSet>
            </UnitsMLType>
          XML
        end

        it "matches the converted xml with the expected xml with a short example" do
          expect(UnitsMLV10CSD04::UnitsMLType.from_xml(xml).to_xml).to be_xml_equivalent_to(xml)
        end

        it "matches the converted xml with the expected xml with a detailed example" do
          expect(UnitsMLV10CSD04::UnitsMLType.from_xml(detailed_xml).to_xml).to be_xml_equivalent_to(detailed_xml)
        end
      end
    end
  end

  describe "SupportedDataTypes.skippable?" do
    # Attribute TypeRefs store the snake_case rendering, simple_content
    # keeps the XSD spelling; skippable? must accept both for dateTime,
    # the one skippable name that changes under snake_case.
    it "matches both the XSD and snake_case spelling of skippable types" do
      sdt = described_class::SupportedDataTypes
      expect(sdt.skippable?("dateTime")).to be true
      expect(sdt.skippable?("date_time")).to be true
    end

    it "still rejects non-skippable types in both spellings" do
      sdt = described_class::SupportedDataTypes
      expect(sdt.skippable?("nonNegativeInteger")).to be false
      expect(sdt.skippable?("non_negative_integer")).to be false
    end
  end
end
