= LutaML Registers

== Introduction

There are three types of registers in Lutaml::Model:

1. *TypeRegister*
2. *ModelRegister*
3. *GlobalRegister*

=== TypeRegister

The TypeRegister is a registry class that registers and looks-up the `Lutaml::Model::Type::Value` classes only.

==== Register a Type::Value class

Following syntax register a `Type::Value` class:
```ruby
# assuming we have a `CustomString` class that inherits from Lutaml::Model::Type::Value
Lutaml::Model::Type.register(:custom_string, Lutaml::Model::Type::CustomString)
```
NOTE: `TypeError` is raised if the class does not inherit from `Lutaml::Model::Type::Value`.

==== Lookup a *Type::Value* class
Lookup a `Type::Value` class using the assigned name:
```ruby
Lutaml::Model::Type.lookup(:custom_string) # returns Lutaml::Model::Type::CustomString
```

NOTE: `Lutaml::Model::Type::UnknownTypeError` is raised if the name is not found in the registry.

When looking up a class, the class is returned without looking up into the registry.
This is useful when you want to use the class directly without going through the registry.
```ruby
Lutaml::Model::Type.lookup(Lutaml::Model::Type::CustomString) # returns Lutaml::Model::Type::CustomString even if it's not registered in the registry
```

=== ModelRegister

The *ModelRegister* is a registry class that registers and looks-up the `Lutaml::Model::Registrable` classes (by default, `Lutaml::Model::Serializable` are `Registrable` classes). For consistency, the `Lutaml::Model::Type::Value` classes are registered in a similar manner, but within the TypeRegister registry, as referenced in the <<TypeRegister,previous section>>.

==== Register a Class

Register a Model class using the following syntax:
```ruby
# assuming we have a `CustomModel` class that inherits from Lutaml::Model::Serializable
Lutaml::Model::Register.register_model(Lutaml::Model::CustomModel, id: :custom_model)
```
This method `register_model` registers the class and assigns it the passed ID, which is `:custom_model` in this case. But, if a model is registered without an ID, the class name is used as the ID. For example:
```ruby
Lutaml::Model::Register.register_model(Lutaml::Model::AnotherCustomModel)
```

This will register the class `AnotherCustomModel` with the ID `:another_custom_model`.

==== Register model tree

The `register_model_tree` method registers all the classes in the provided Model's heirarchy. For example:
```ruby
class Math < Lutaml::Model::Serializable
  attribute :mrow, Mrow
  attribute :mstyle, Mstyle
end

class Mrow < Lutaml::Model::Serializable
  attribute :mstyle, Mstyle
end

class Mstyle < Lutaml::Model::Serializable
  attribute :mrow, Mrow
end

Lutaml::Model::Register.register_model_tree(Math) # registers all the classes in the Math model tree, in this case Mstyle and Mrow
```


=== GlobalRegister
The GlobalRegister is a singleton that registers all the ModelRegisters.

ModelRegisters can be registered using following syntax:

```ruby
v1_register = Lutaml::Model::Register.new(:v1)
global_register = Lutaml::Model::GlobalRegister
global_register.register(v1_register) # register a Model register
# OR
global_register.instance.register(v1_register) # register a Model register
```

The `register` method registers the ModelRegister based on it's ID. The ID is used to look up the ModelRegister using the following syntax:
```ruby
global_register.lookup(:v2) # fetch a Model register
# OR
global_register.instance.lookup(:v2) # fetch a Model register
```

If a register is not needed anymore, it can be removed using the following syntax:
```ruby
global_register.remove(:v1) # remove a ModelRegister using the it's ID
# OR
global_register.instance.remove(:v1) # remove a ModelRegister using the it's ID
```