# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-asciidoc'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'just-the-docs'

group :jekyll_plugins do
  gem 'asciidoctor'
end
