name: dependent-gems-test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths-ignore:
      - '**.adoc'
  pull_request:
    paths-ignore:
      - '**.adoc'
  workflow_dispatch:
  repository_dispatch:
    types: [ release-passed ]

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/dependent-rake.yml@fix/add-pat-token
    with:
      command: bundle exec rspec
    secrets:
      pat_token: ${{ secrets.LUTAML_CI_PAT_TOKEN }}
