name: dependent-gems-test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths-ignore:
      - '**.adoc'
  pull_request:
    paths-ignore:
      - '**.adoc'
  workflow_dispatch:
  repository_dispatch:
    types: [ release-passed ]

jobs:
  rake:
    # TODO: revert to @main after metanorma/ci merges the setup-tools-in-dependent-rake changes
    uses: metanorma/ci/.github/workflows/dependent-rake.yml@setup-tools-in-dependent-rake
    with:
      command: bundle exec rspec
    secrets:
      pat_token: ${{ secrets.LUTAML_CI_PAT_TOKEN }}
      setup-tools: 'inkscape, ghostscript, exiftool'
      after-setup-ruby: |
        if [ -f frontend/package.json ]; then cd frontend && npm install && npm run build; fi
