name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'
  repository_dispatch:
    types: [ do-release ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  bump:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.next_version != 'skip'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.LUTAML_CI_PAT_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: gem install gem-release

      - run: gem bump --version ${{ github.event.inputs.next_version }} --tag --push

  release:
    if: github.event_name == 'repository_dispatch'
    uses: metanorma/ci/.github/workflows/rubygems-release.yml@main
    with:
      next_version: skip
      post_install: |
        git status
        cat .bundle/config
    secrets:
      rubygems-api-key: ${{ secrets.LUTAML_CI_RUBYGEMS_API_KEY }}
      pat_token: ${{ secrets.LUTAML_CI_PAT_TOKEN }}
